# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://blakkksabbath.github.io
baseurl:             
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Jithendra Yenugula
  url:               https://twitter.com/jithendrabsy
  email:             jithendrabsy@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
